name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "registry.alioth.center"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.registry.alioth.center", custom_domain = true },
  { pattern = "quay.registry.alioth.center", custom_domain = true },
  { pattern = "gcr.registry.alioth.center", custom_domain = true },
  { pattern = "k8s-gcr.registry.alioth.center", custom_domain = true },
  { pattern = "k8s.registry.alioth.center", custom_domain = true },
  { pattern = "ghcr.registry.alioth.center", custom_domain = true },
  { pattern = "cloudsmith.registry.alioth.center", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
